### PR TITLE
Rocky9

### PR DESCRIPTION
**Pull request by pwalczysko**
Possibly the changes are too drastic:

 1. Removed the interpreter-p2 as it seems to me this is outdated - but of course might be wrong
 2. Did not enable the rockylinux-9 test on interpreter-p3 as could not make them work - the comment on the https://github.com/ome/ansible-role-python3-virtualenv/blob/12d7d6ce06d18d3a4c5f9090eab203d839585fd4/molecule/interpreter-py3/molecule.yml#L11 seems accurrate in my hands when uncommenting and replacing the CentOS 7 with Rocky 9 (and failing the test https://github.com/pwalczysko/ansible-role-python3-virtualenv/actions/runs/6328841273/job/17187902045) .

cc @sbesson @jburel @khaledk2

### CODE REVIEW

**Comment by pwalczysko** [comment]
the tests are on https://github.com/pwalczysko/ansible-role-python3-virtualenv/actions - not sure how to enable them here, it seems that closing and reopening the PR does not help @jburel

**Comment by jburel** [comment]
The job was turned off. Running now

**Review by sbesson — CHANGES_REQUESTED** [review]
> Removed the interpreter-p2 as it seems to me this is outdated - but of course might be wrong

I believe this logic was introduced during the migration to Python 3 in OMERO 5.6 and allowed to support systems like CentOS 7 where Python 2.x is the default version.

The migration to support the el9/ubuntu22.04 families feels like a good time to revisit these assumptions and get rid of unnecessary logic. 

If we go down that path, a couple of additional changes worth looking into:
- we should be able to get rid of the `install python2-setuptools for python2 interpreter` tasks in redhat.yml and debian.yml
- the `interpreter-py3` scenario might be simply renamed as `default`
- the fact tests are not running with Python 3 as the interpreter on Rocky Linux 9 is slightly concerning. Immediate thought is that it could be worth installing other prerequisites as in https://github.com/ome/ansible-role-python3-virtualenv/blob/12d7d6ce06d18d3a4c5f9090eab203d839585fd4/tasks/debian.yml#L8-L12 in `redhat.yml` like `python3-pip` and `python3-setuptools` to see if this resolves the issue

**Comment by pwalczysko** [comment]
> > Removed the interpreter-p2 as it seems to me this is outdated - but of course might be wrong
> 
> I believe this logic was introduced during the migration to Python 3 in OMERO 5.6 and allowed to support systems like CentOS 7 where Python 2.x is the default version.
> 
> The migration to support the el9/ubuntu22.04 families feels like a good time to revisit these assumptions and get rid of unnecessary logic.
> 
> If we go down that path, a couple of additional changes worth looking into:
> 
>     * we should be able to get rid of the `install python2-setuptools for python2 interpreter` tasks in redhat.yml and debian.yml
> 
>     * the `interpreter-py3` scenario might be simply renamed as `default`
> 
>     * the fact tests are not running with Python 3 as the interpreter on Rocky Linux 9 is slightly concerning. Immediate thought is that it could be worth installing other prerequisites as in https://github.com/ome/ansible-role-python3-virtualenv/blob/12d7d6ce06d18d3a4c5f9090eab203d839585fd4/tasks/debian.yml#L8-L12
>        in `redhat.yml` like `python3-pip` and `python3-setuptools` to see if this resolves the issue

@sbesson Fixes of all points pushed accordingly, see https://github.com/ome/ansible-role-python3-virtualenv/pull/4/commits/3644ed12656d4264eb8cb9f4068a61d918c01087 to https://github.com/ome/ansible-role-python3-virtualenv/pull/4/commits/56bd9c82c0298acc6ff33a232be5d93824fe4645.

 - the structure is cleaned up as requested
 - the Rocky9 test is repurposed from the previously commented-out CentOS  7 test as requested
 - test is passing

**Review by sbesson — APPROVED** [review]
Thanks @pwalczysko. Much simpler overall and symmetrical between Ubuntu and RedHat as well as removing the old Python 2 compatibility.

No objection from my side. We might need to increment the major version number and possibly update the README to communicate the backwards incompatible nature of the role changes.

**Pull request merged**
